apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron-support-bundle
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: kotsadm
          automountServiceAccountToken: true
          containers:
          - name: cron-support-bundle
            image: replicated/troubleshoot:0.48.0
            imagePullPolicy: IfNotPresent
            command:
            - /troubleshoot/support-bundle
            - --interactive=false
            - secret/sentry-pro-gecko/support-bundle-secret
          restartPolicy: OnFailure