apiVersion: v1
kind: Secret
metadata:
  name: support-bundle-secret
type: Opaque
stringData:
  support-bundle-spec: |-
    apiVersion: troubleshoot.sh/v1beta2
    kind: SupportBundle
    metadata:
      annotations:
        kots.io/exclude: "true"
      creationTimestamp: null
      name: support-bundle-secret
    spec:
      collectors:
      - clusterInfo: {}
      - clusterResources: {}